// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Todo struct {
	TodoID    int64          `json:"todo_id"`
	UserID    int32          `json:"user_id"`
	Title     sql.NullString `json:"title"`
	Time      sql.NullString `json:"time"`
	Date      sql.NullString `json:"date"`
	Completed sql.NullString `json:"completed"`
}

type User struct {
	UserID    int64          `json:"user_id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	UserName  sql.NullString `json:"user_name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
}
